const BlogApi = [
    {
      id: 1,
      image: "https://www2.deloitte.com/content/dam/html/us/deloitte-university/current-release/imgs/Phase-01/history-of-DU-ORIG-AS-edited.jpg",
      date: "August 2022",
      title_one: "MLT Summer Seminar",
      desc_one: "Talk about summer seminar & prep work",
      title_two: "Companies & Networking",
      desc_two: "Talk about company reps & table talks",
      title_three: "Intuit Case",
      desc_three: "Talk about Intuit case study",
    },
    {
      id: 2,
      image: "https://company.clearchanneloutdoor.com/wp-content/uploads/2014/02/morgan-stanley-times-square.jpg",
      date: "April 2022",
      title_one: "Morgan Stanley Early Insights",
      desc_one: "Talk",
      title_two: "Technology",
      desc_two: "Talk about tech talks & workshops",
      title_three: "Speakers & Connections",
      desc_three: "Talk about connections & networking",
    },
    {
      id: 3,
      image: "https://www.salesforce.com/news/wp-content/uploads/sites/3/2022/02/1440-Main-Campus-Sign.jpg?w=1024",
      date: "March 2022",
      title_one: "Salesforce B.A.S.E. Camp",
      desc_one: "As a B.A.S.E. Camp fellow, I was selected to participate in a multi-day, immersive learning experience hosted at Salesforce's Trailblazer Ranch in northern California. This program was designed for students to connect with other computer science majors from schools around the nation, participate in skill-building workshops, impactful volunteer activities, and learn more about early career opportunities in tech.",
      title_two: "Camp Fellow",
      desc_two: "As participants in the program, we stayed at the newly opened Trailblazer Ranch on the 1440 Multiversity campus, surrounded by beautiful California wildlife! Through wilderness hikes, nature walks, and scavenger hunts, we were able to make the most out of our time here. While at B.A.S.E. Camp, we were introduced to Salesforce’s products and who they are as a company. We were able to learn about their history, core values, and also got to hear panels full of current employees depicting what it was like to work at Salesforce. We were led through activities such as their goal setting framework V2MOM, which stands for Vision, Values, Method, Obstacles, and Measures as well as pitching brand redesigns using Salesforce technology. One of the best parts of B.A.S.E. camp was the strong community and friendship we built while at TrThe fun continued with Salesforce trivia and two team challenges—a Chopped-style cooking challenge, and a shelter building wilderness challenge!",
      title_three: "Volunteer",
      desc_three: "During our time at B.A.S.E. camp, we had the amazing opportunity to volunteer with Housing Matters: an organization that partners with individuals and familities in the Santa Cruz county area to create pathways out of their homelessness adn into permanent housing. We were able to assemble 1,000 kits filled with personal care products for induvudlas who stop by their camput to use their day services. Overall, B.A.S.E. camp was an amazing experience and gave me the opportunrity to connect with many other students from across the country. ",
    },
  ]
  export default BlogApi