const TestimonialApi = [
    {
      id: 1,
      image: "https://www.thn.org/wp-content/uploads/2020/11/jwj-Homeless-1417.jpg",
      design: "WEB DEVELOPMENT",
      name: "Homelessness in Austin",
      offcer: "HTML, CSS, JavaScript, & python flask",
      post: "Web App Development",
      date: "Nov 2019 - Feb 2020",
      desc: "As a part of the Code2College curriculum, students design and build a web application capstone project. For my project, I created this website to raise awareness about the homelessness crisis in Austin and ways the community can help.",
      link: "https://areye2020.pythonanywhere.com/",
    },
    {
      id: 2,
      image: "https://static.vecteezy.com/system/resources/previews/000/166/399/original/vector-dentist-line-icon-pack.jpg",
      design: "WEB DEVELOPMENT",
      name: "Dr. Gita Yitta",
      offcer: "HTML, CSS, & JavaScript",
      post: "Web App Development",
      date: "Mar 2020 - Apr 2020",
      desc: "During the height of the COVID pandemic, Code2College students had the opportunity to create a website for an industry professional who are doing good in their communities. This website was made for Dr. Gita Yitta: a public health leader and entrepreneur actively involved in public health in Southern Oregon.",
      link: "https://dentist3.c2cstudents.org",
    },
    {
      id: 3,
      image: "https://t3.ftcdn.net/jpg/03/24/08/20/360_F_324082017_07zHI5vADcE9XxfIKpdmnJOOrj6HcIRS.jpg",
      design: "JAVA DEVELOPMENT",
      name: "Tetris",
      offcer: "Java, Data Structures",
      post: "Java Development",
      date: "Nov 2020",
      desc: "During my data structures course, we were asked to implement a version of the Tetris game, by breaking the whole game into smaller components that could be independently tested: TetrisPiece (each individual piece), TetrisBoard (the TetrisPieces in context of the board), and MassiveBrain (a computer algorithm which plays the game).",
      link: "https://areye2020.pythonanywhere.com/",
    },
    {
      id: 4,
      image: "https://iq.opengenus.org/content/images/2019/04/memory_c.jpg",
      design: "MEMORY MANAGER",
      name: "Dynamic Storage Allocator",
      offcer: "C, Computer Architecture",
      post: "Computer Architecture",
      date: "Mar 2021",
      desc: "During my Computer Architecture Course, we were asked to create a dynamic storage allocator for C programs. The project was to create our own version of the malloc and free routines; my design was to use external fragmentation and block merging) since the OtherBlocks can be coalesced without going through the whole list looking for free blocks.",
      link: "https://dentist3.c2cstudents.org",
    },
  ]
  
  export default TestimonialApi